# Generated by Django 5.2.16 on 2026-08-03 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobsearch', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cv', 'Tailored CV'), ('cover_letter', 'Cover letter'), ('qa', 'Application Q&A')], max_length=20)),
                ('prompt_question', models.TextField(blank=True, help_text='Only set for Q&A drafts')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='jobsearch.job')),
                ('source_documents', models.ManyToManyField(blank=True, to='portfolio.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
