# Generated by Django 5.2.16 on 2026-08-03 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'UK Data/BI roles'", max_length=100)),
                ('keywords', models.CharField(help_text="Comma-separated job titles/keywords, e.g. 'data analyst, business analyst'", max_length=300)),
                ('location', models.CharField(blank=True, help_text="City, or 'remote'", max_length=150)),
                ('country_code', models.CharField(default='GB', max_length=2)),
                ('job_type', models.CharField(blank=True, choices=[('', 'Any'), ('fulltime', 'Full-time'), ('parttime', 'Part-time'), ('contract', 'Contract'), ('temporary', 'Temporary')], max_length=20)),
                ('salary_mode', models.CharField(choices=[('going_rate', 'Occupation going-rate table'), ('flat_minimum', 'Flat minimum salary')], default='going_rate', max_length=20)),
                ('flat_minimum_salary', models.PositiveIntegerField(blank=True, help_text='Only used when salary_mode = flat_minimum', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThresholdRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_match', models.CharField(help_text="Job title/keyword this row applies to, e.g. 'data analyst'", max_length=150)),
                ('occupation_code', models.CharField(blank=True, help_text='e.g. SOC 3544', max_length=50)),
                ('threshold_amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('verified', models.BooleanField(default=False, help_text='Whether this figure has been checked against an official source')),
                ('source_note', models.CharField(blank=True, max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threshold_rows', to='jobsearch.criteriaprofile')),
            ],
            options={
                'ordering': ['keyword_match'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('adzuna', 'Adzuna'), ('reed', 'Reed'), ('manual', 'Manually added')], default='manual', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('compensation_raw', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('new', 'New'), ('interested', 'Interested'), ('tailoring', 'Tailoring'), ('applied', 'Applied'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('sponsor_status', models.CharField(choices=[('unknown', 'Unknown'), ('likely', 'Likely'), ('confirmed', 'Confirmed'), ('no', 'No')], default='unknown', max_length=20)),
                ('threshold_pass', models.BooleanField(blank=True, help_text='Whether compensation clears the matched threshold row', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobsearch.criteriaprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('owner', 'source', 'external_id'), name='unique_job_per_owner_source')],
            },
        ),
    ]
