# Generated by Django 5.2.16 on 2026-08-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriaprofile',
            name='include_sponsorship_keyword',
            field=models.BooleanField(default=False, help_text="Also search 'visa sponsorship' as an extra term, to surface postings that explicitly mention it. Weak signal - most sponsor-eligible jobs don't say so in the text. See the going-rate table and sponsor-status column for the more reliable checks."),
        ),
        migrations.CreateModel(
            name='SponsorRegisterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=300)),
                ('organisation_name_normalized', models.CharField(max_length=300)),
                ('town_city', models.CharField(blank=True, max_length=150)),
                ('county', models.CharField(blank=True, max_length=150)),
                ('rating', models.CharField(blank=True, help_text="'Type & Rating' column, e.g. 'Worker (A rating)'", max_length=100)),
                ('route', models.CharField(blank=True, help_text="e.g. 'Skilled Worker'", max_length=150)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['organisation_name_normalized'], name='jobsearch_s_organis_fea701_idx')],
            },
        ),
    ]
