# Generated by Django 5.2.16 on 2026-08-03 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('doc_type', models.CharField(choices=[('cv', 'CV / Resume'), ('certificate', 'Certificate'), ('project', 'Project write-up'), ('other', 'Other')], default='other', max_length=20)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated, e.g. 'python, sql, agile'", max_length=300)),
                ('body_text', models.TextField(blank=True, help_text='Pasted text content - what the AI layer actually reads.')),
                ('file', models.FileField(blank=True, null=True, upload_to='portfolio/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
